"""
IMIS Database Configuration Helper
Generates secure keys and tests database connection
"""
import secrets
import sys
import os

def generate_secret_key():
    """Generate a secure random secret key"""
    return secrets.token_urlsafe(32)

def create_database_url():
    """Interactive database URL creator"""
    print("\n" + "="*60)
    print("IMIS Database Configuration Helper")
    print("="*60 + "\n")
    
    print("Enter your cPanel PostgreSQL database details:\n")
    
    host = input("Database Host (e.g., server.host.com): ").strip()
    port = input("Database Port [5432]: ").strip() or "5432"
    database = input("Database Name (e.g., cpanel_user_imis_production): ").strip()
    username = input("Database Username (e.g., cpanel_user_imis_user): ").strip()
    password = input("Database Password: ").strip()
    
    # Generate secret key
    secret_key = generate_secret_key()
    
    # Create DATABASE_URL
    database_url = f"postgresql://{username}:{password}@{host}:{port}/{database}"
    
    print("\n" + "="*60)
    print("Configuration Generated!")
    print("="*60 + "\n")
    
    print("Add these to your backend/.env file:\n")
    print(f"DATABASE_URL={database_url}")
    print(f"SECRET_KEY={secret_key}")
    print("\n" + "="*60 + "\n")
    
    # Save to file
    save = input("Save to backend/.env.cpanel? (y/n): ").strip().lower()
    if save == 'y':
        env_content = f"""# IMIS cPanel Production Configuration
# Generated by setup_cpanel_db.py

DATABASE_URL={database_url}
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# MTN Mobile Money
MTN_MOMO_ENABLED=true
MTN_MOMO_ENVIRONMENT=production
MTN_MOMO_BASE_URL=https://proxy.momoapi.mtn.co.rw
MTN_MOMO_SUBSCRIPTION_KEY=92e0ee9794d34ac8bb166d2cd3b99a69
MTN_MOMO_API_USER=24a14d7b-57b2-46a6-ba5c-4c17f628eb9e
MTN_MOMO_API_KEY=2ac93c3f60304fdaa6f9ad2f591f0834
MTN_MOMO_TARGET_ENVIRONMENT=mtnrwanda
MTN_MOMO_ACCOUNT=FRI:41414644/MM

# Payment Settings
UNLOCK_FEE=1000.0
COMMISSION_RATE=0.10
PAYMENT_TIMEOUT_SECONDS=300

# Frontend URL (UPDATE THIS!)
FRONTEND_URL=https://yourdomain.com

# CORS (UPDATE THIS!)
ALLOWED_ORIGINS=https://yourdomain.com

# Logging
LOG_LEVEL=INFO
"""
        
        with open('backend/.env.cpanel', 'w') as f:
            f.write(env_content)
        
        print("Configuration saved to backend/.env.cpanel")
        print("Copy this to backend/.env when deploying\n")

def test_connection():
    """Test database connection"""
    print("\n" + "="*60)
    print("Testing Database Connection")
    print("="*60 + "\n")
    
    try:
        from sqlalchemy import create_engine, text
        
        # Load DATABASE_URL from environment or prompt
        database_url = os.getenv('DATABASE_URL')
        if not database_url:
            database_url = input("Enter DATABASE_URL to test: ").strip()
        
        print(f"Connecting to: {database_url.split('@')[1] if '@' in database_url else 'database'}...")
        
        engine = create_engine(database_url)
        
        # Handle different database types
        connect_args = {}
        if 'postgresql' in database_url:
            connect_args = {"sslmode": "disable"}
        
        engine = create_engine(database_url, connect_args=connect_args)
        
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version();"))
            version = result.fetchone()[0]
            print(f"\nConnection successful!")
            print(f"PostgreSQL Version: {version[:50]}...\n")
            
    except Exception as e:
        print(f"\nConnection failed!")
        print(f"Error: {str(e)}\n")
        print("Troubleshooting:")
        print("1. Check if Remote Database Access has your IP added")
        print("2. Verify database credentials are correct")
        print("3. Ensure PostgreSQL port 5432 is accessible")
        print("4. Check if database and user exist in cPanel\n")

if __name__ == "__main__":
    print("\nIMIS Database Setup for cPanel\n")
    print("Choose an option:")
    print("1. Generate database configuration")
    print("2. Test database connection")
    print("3. Both")
    
    choice = input("\nEnter choice (1-3): ").strip()
    
    if choice in ['1', '3']:
        create_database_url()
    
    if choice in ['2', '3']:
        test_connection()
    
    print("\nSetup complete!")
    print("See CPANEL_DATABASE_SETUP.md for detailed instructions\n")
